name: 问题反馈
description: File a bug report
title: "[错误报告]: 请在此处简单描述你的问题"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        请确认以下信息：
        1. 请按此模板提交issues，不按模板提交的问题将直接关闭。
        2. 如果你的问题可以直接在以往 issue 中找到，那么你的 issue 将会被直接关闭。
        3. **$\color{red}{提交问题务必描述清楚、附上日志}$**，描述不清导致无法理解和分析的问题会被直接关闭。
        5. **$\color{red}{不要通过issues来寻求解决你的环境问题、配置安装类问题、咨询类问题}$**，否则直接关闭并加入用户 $\color{red}{黑名单}$ !实在没有精力陪一波又一波的伸手党玩。
  - type: checkboxes
    id: ensure
    attributes:
      label: 确认
      description: 在提交 issue 之前，请确认你已经阅读并确认以下内容
      options:
        - label: 我的版本是最新版本，我的版本号与 [version](https://github.com/Akimio521/MediaWarp/releases/latest) 相同。
          required: true
        - label: 我已经 [issue](https://github.com/Akimio521/MediaWarp/issues) 中搜索过，确认我的问题没有被提出过。
          required: true
        - label: 我已经修改标题，将标题中的 描述 替换为我遇到的问题。
          required: true

  - type: input
    id: version
    attributes:
      label: 当前程序版本
      description: 遇到问题时程序所在的版本号
    validations:
      required: true
  - type: input
    id: version-info
    attributes:
      label: 当前程序版本的详细信息
      description: 访问 `http://<MediaWarp ip>:<port>/MediaWarp/version` 或通过 `./MediaWarp --version` 获取
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: 运行环境
      description: 当前程序运行环境
      options:
        - Docker
        - Windows
        - Linux
        - MacOS
    validations:
      required: true
  - type: dropdown
    id: mediaserver
    attributes:
      label: 媒体服务器类型
      description: 上游媒体服务器类型
      options:
        - Emby
        - Jellyfin
    validations:
      required: true
  - type: input
    id: mediaserver-version
    attributes:
      label: 媒体服务器版本
      description: 上游媒体服务器版本（如果使用 docker 最好可以提供详细标签信息，例如`linuxserver/emby:4.9.0-beta`）
    validations:
      required: true
  - type: input
    id: client-version
    attributes:
      label: 客户端版本
      description: 使用的客户端版本及版本号（Fileball/238 CFNetwork/1410.0.3 Darwin/22.6.0、Infuse-Direct/7.8、Emby/3.2.32-17.41 (Linux;Android 14) ExoPlayerLib/2.13.2）
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: 问题类型
      description: 你在以下哪个部分碰到了问题
      options:
        - Strm 文件播放问题
        - Web 美化/额外功能问题
        - 配置文件读取问题
        - 其他问题
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 问题描述
      description: 请详细描述你碰到的问题
      placeholder: "问题描述"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 发生问题时相关日志
      description: 问题出现时，程序运行日志请复制到这里。
      render: bash
  - type: textarea
    id: config
    attributes:
      label: 发生问题时配置文件
      description: 问题出现时，程序配置文件请复制到这里。
      render: yaml
