package schemas_emby

// MediaStream
type MediaStream struct {
	AspectRatio                     *string                 `json:"AspectRatio,omitempty"`
	AttachmentSize                  *int64                  `json:"AttachmentSize"`
	AverageFrameRate                *float64                `json:"AverageFrameRate"`
	BitDepth                        *int64                  `json:"BitDepth"`
	BitRate                         *int64                  `json:"BitRate"`
	ChannelLayout                   *string                 `json:"ChannelLayout,omitempty"`
	Channels                        *int64                  `json:"Channels"`
	Codec                           *string                 `json:"Codec,omitempty"`
	CodecTag                        *string                 `json:"CodecTag,omitempty"`
	ColorPrimaries                  *string                 `json:"ColorPrimaries,omitempty"`
	ColorSpace                      *string                 `json:"ColorSpace,omitempty"`
	ColorTransfer                   *string                 `json:"ColorTransfer,omitempty"`
	Comment                         *string                 `json:"Comment,omitempty"`
	DeliveryMethod                  *SubtitleDeliveryMethod `json:"DeliveryMethod,omitempty"`
	DeliveryURL                     *string                 `json:"DeliveryUrl,omitempty"`
	DisplayLanguage                 *string                 `json:"DisplayLanguage,omitempty"`
	DisplayTitle                    *string                 `json:"DisplayTitle,omitempty"`
	ExtendedVideoSubType            *ExtendedVideoSubTypes  `json:"ExtendedVideoSubType,omitempty"`
	ExtendedVideoSubTypeDescription *string                 `json:"ExtendedVideoSubTypeDescription,omitempty"`
	ExtendedVideoType               *ExtendedVideoTypes     `json:"ExtendedVideoType,omitempty"`
	Extradata                       *string                 `json:"Extradata,omitempty"`
	Height                          *int64                  `json:"Height"`
	Index                           *int64                  `json:"Index,omitempty"`
	IsAnamorphic                    *bool                   `json:"IsAnamorphic"`
	IsAVC                           *bool                   `json:"IsAVC"`
	IsDefault                       *bool                   `json:"IsDefault,omitempty"`
	IsExternal                      *bool                   `json:"IsExternal,omitempty"`
	IsExternalURL                   *bool                   `json:"IsExternalUrl"`
	IsForced                        *bool                   `json:"IsForced,omitempty"`
	IsHearingImpaired               *bool                   `json:"IsHearingImpaired,omitempty"`
	IsInterlaced                    *bool                   `json:"IsInterlaced,omitempty"`
	IsTextSubtitleStream            *bool                   `json:"IsTextSubtitleStream,omitempty"`
	ItemID                          *string                 `json:"ItemId,omitempty"`
	Language                        *string                 `json:"Language,omitempty"`
	Level                           *float64                `json:"Level"`
	MIMEType                        *string                 `json:"MimeType,omitempty"`
	NalLengthSize                   *string                 `json:"NalLengthSize,omitempty"`
	Path                            *string                 `json:"Path,omitempty"`
	PixelFormat                     *string                 `json:"PixelFormat,omitempty"`
	Profile                         *string                 `json:"Profile,omitempty"`
	Protocol                        *MediaProtocol          `json:"Protocol,omitempty"`
	RealFrameRate                   *float64                `json:"RealFrameRate"`
	RefFrames                       *int64                  `json:"RefFrames"`
	Rotation                        *int64                  `json:"Rotation"`
	SampleRate                      *int64                  `json:"SampleRate"`
	ServerID                        *string                 `json:"ServerId,omitempty"`
	StreamStartTimeTicks            *int64                  `json:"StreamStartTimeTicks"`
	SubtitleLocationType            *SubtitleLocationType   `json:"SubtitleLocationType,omitempty"`
	SupportsExternalStream          *bool                   `json:"SupportsExternalStream,omitempty"`
	TimeBase                        *string                 `json:"TimeBase,omitempty"`
	Title                           *string                 `json:"Title,omitempty"`
	Type                            *MediaStreamType        `json:"Type,omitempty"`
	VideoRange                      *string                 `json:"VideoRange,omitempty"`
	Width                           *int64                  `json:"Width"`
}
