// UsersItemsDetailResponse.go

package schemas_emby

// /Users/:userID/Items/:itemID的响应
type UsersItemsDetailResponse struct {
	AffiliateCallSign            *string                   `json:"AffiliateCallSign,omitempty"`
	AirDays                      []DayOfWeek               `json:"AirDays,omitempty"`
	Album                        *string                   `json:"Album,omitempty"`
	AlbumArtist                  *string                   `json:"AlbumArtist,omitempty"`
	AlbumArtists                 []NameIDPair              `json:"AlbumArtists,omitempty"`
	AlbumCount                   *int64                    `json:"AlbumCount"`
	AlbumID                      *string                   `json:"AlbumId,omitempty"`
	AlbumPrimaryImageTag         *string                   `json:"AlbumPrimaryImageTag,omitempty"`
	Altitude                     *float64                  `json:"Altitude"`
	Aperture                     *float64                  `json:"Aperture"`
	ArtistItems                  []NameIDPair              `json:"ArtistItems,omitempty"`
	Artists                      []string                  `json:"Artists,omitempty"`
	AsSeries                     *bool                     `json:"AsSeries"`
	BackdropImageTags            []string                  `json:"BackdropImageTags,omitempty"`
	Bitrate                      *int64                    `json:"Bitrate"`
	CameraMake                   *string                   `json:"CameraMake,omitempty"`
	CameraModel                  *string                   `json:"CameraModel,omitempty"`
	CanDelete                    *bool                     `json:"CanDelete"`
	CanDownload                  *bool                     `json:"CanDownload"`
	CanEditItems                 *bool                     `json:"CanEditItems"`
	CanLeaveContent              *bool                     `json:"CanLeaveContent"`
	CanMakePublic                *bool                     `json:"CanMakePublic"`
	CanManageAccess              *bool                     `json:"CanManageAccess"`
	ChannelID                    *string                   `json:"ChannelId,omitempty"`
	ChannelName                  *string                   `json:"ChannelName,omitempty"`
	ChannelNumber                *string                   `json:"ChannelNumber,omitempty"`
	ChannelPrimaryImageTag       *string                   `json:"ChannelPrimaryImageTag,omitempty"`
	Chapters                     []ChapterInfo             `json:"Chapters,omitempty"`
	ChildCount                   *int64                    `json:"ChildCount"`
	CollectionType               *string                   `json:"CollectionType,omitempty"`
	CommunityRating              *float64                  `json:"CommunityRating"`
	CompletionPercentage         *float64                  `json:"CompletionPercentage"`
	Composers                    []NameIDPair              `json:"Composers,omitempty"`
	Container                    *string                   `json:"Container,omitempty"`
	CriticRating                 *float64                  `json:"CriticRating"`
	CurrentProgram               *UsersItemsDetailResponse `json:"CurrentProgram,omitempty"`
	CustomRating                 *string                   `json:"CustomRating,omitempty"`
	DateCreated                  *string                   `json:"DateCreated"`
	Disabled                     *bool                     `json:"Disabled"`
	DisplayOrder                 *string                   `json:"DisplayOrder,omitempty"`
	DisplayPreferencesID         *string                   `json:"DisplayPreferencesId,omitempty"`
	EndDate                      *string                   `json:"EndDate"`
	EpisodeTitle                 *string                   `json:"EpisodeTitle,omitempty"`
	Etag                         *string                   `json:"Etag,omitempty"`
	ExposureTime                 *float64                  `json:"ExposureTime"`
	ExternalUrls                 []ExternalURL             `json:"ExternalUrls,omitempty"`
	ExtraType                    *string                   `json:"ExtraType,omitempty"`
	FileName                     *string                   `json:"FileName,omitempty"`
	FocalLength                  *float64                  `json:"FocalLength"`
	ForcedSortName               *string                   `json:"ForcedSortName,omitempty"`
	GameSystem                   *string                   `json:"GameSystem,omitempty"`
	GameSystemID                 *int64                    `json:"GameSystemId"`
	GenreItems                   []NameLongIDPair          `json:"GenreItems,omitempty"`
	Genres                       []string                  `json:"Genres,omitempty"`
	GUID                         *string                   `json:"Guid,omitempty"`
	Height                       *int64                    `json:"Height"`
	ID                           *string                   `json:"Id,omitempty"`
	ImageOrientation             *DrawingImageOrientation  `json:"ImageOrientation,omitempty"`
	ImageTags                    map[string]string         `json:"ImageTags,omitempty"`
	IndexNumber                  *int64                    `json:"IndexNumber"`
	IndexNumberEnd               *int64                    `json:"IndexNumberEnd"`
	IsFolder                     *bool                     `json:"IsFolder"`
	IsKids                       *bool                     `json:"IsKids"`
	IsLive                       *bool                     `json:"IsLive"`
	IsMovie                      *bool                     `json:"IsMovie"`
	IsNew                        *bool                     `json:"IsNew"`
	IsNews                       *bool                     `json:"IsNews"`
	ISOSpeedRating               *int64                    `json:"IsoSpeedRating"`
	IsPremiere                   *bool                     `json:"IsPremiere"`
	IsRepeat                     *bool                     `json:"IsRepeat"`
	IsSeries                     *bool                     `json:"IsSeries"`
	IsSports                     *bool                     `json:"IsSports"`
	Latitude                     *float64                  `json:"Latitude"`
	ListingsChannelID            *string                   `json:"ListingsChannelId,omitempty"`
	ListingsChannelName          *string                   `json:"ListingsChannelName,omitempty"`
	ListingsChannelNumber        *string                   `json:"ListingsChannelNumber,omitempty"`
	ListingsID                   *string                   `json:"ListingsId,omitempty"`
	ListingsPath                 *string                   `json:"ListingsPath,omitempty"`
	ListingsProviderID           *string                   `json:"ListingsProviderId,omitempty"`
	LocalTrailerCount            *int64                    `json:"LocalTrailerCount"`
	LocationType                 *LocationType             `json:"LocationType,omitempty"`
	LockData                     *bool                     `json:"LockData"`
	LockedFields                 []MetadataFields          `json:"LockedFields,omitempty"`
	Longitude                    *float64                  `json:"Longitude"`
	ManagementID                 *string                   `json:"ManagementId,omitempty"`
	MediaSources                 []MediaSourceInfo         `json:"MediaSources,omitempty"`
	MediaStreams                 []MediaStream             `json:"MediaStreams,omitempty"`
	MediaType                    *string                   `json:"MediaType,omitempty"`
	MovieCount                   *int64                    `json:"MovieCount"`
	MusicVideoCount              *int64                    `json:"MusicVideoCount"`
	Name                         *string                   `json:"Name,omitempty"`
	Number                       *string                   `json:"Number,omitempty"`
	OfficialRating               *string                   `json:"OfficialRating,omitempty"`
	OriginalTitle                *string                   `json:"OriginalTitle,omitempty"`
	Overview                     *string                   `json:"Overview,omitempty"`
	ParentBackdropImageTags      []string                  `json:"ParentBackdropImageTags,omitempty"`
	ParentBackdropItemID         *string                   `json:"ParentBackdropItemId,omitempty"`
	ParentID                     *string                   `json:"ParentId,omitempty"`
	ParentIndexNumber            *int64                    `json:"ParentIndexNumber"`
	ParentLogoImageTag           *string                   `json:"ParentLogoImageTag,omitempty"`
	ParentLogoItemID             *string                   `json:"ParentLogoItemId,omitempty"`
	ParentThumbImageTag          *string                   `json:"ParentThumbImageTag,omitempty"`
	ParentThumbItemID            *string                   `json:"ParentThumbItemId,omitempty"`
	PartCount                    *int64                    `json:"PartCount"`
	Path                         *string                   `json:"Path,omitempty"`
	People                       []BaseItemPerson          `json:"People,omitempty"`
	PlaylistItemID               *string                   `json:"PlaylistItemId,omitempty"`
	PreferredMetadataCountryCode *string                   `json:"PreferredMetadataCountryCode,omitempty"`
	PreferredMetadataLanguage    *string                   `json:"PreferredMetadataLanguage,omitempty"`
	Prefix                       *string                   `json:"Prefix,omitempty"`
	PremiereDate                 *string                   `json:"PremiereDate"`
	PresentationUniqueKey        *string                   `json:"PresentationUniqueKey,omitempty"`
	PrimaryImageAspectRatio      *float64                  `json:"PrimaryImageAspectRatio"`
	PrimaryImageItemID           *string                   `json:"PrimaryImageItemId,omitempty"`
	PrimaryImageTag              *string                   `json:"PrimaryImageTag,omitempty"`
	ProductionLocations          []string                  `json:"ProductionLocations,omitempty"`
	ProductionYear               *int64                    `json:"ProductionYear"`
	ProviderIDS                  map[string]string         `json:"ProviderIds,omitempty"`
	RecursiveItemCount           *int64                    `json:"RecursiveItemCount"`
	RemoteTrailers               []MediaURL                `json:"RemoteTrailers,omitempty"`
	RunTimeTicks                 *int64                    `json:"RunTimeTicks"`
	SeasonID                     *string                   `json:"SeasonId,omitempty"`
	SeasonName                   *string                   `json:"SeasonName,omitempty"`
	SeriesCount                  *int64                    `json:"SeriesCount"`
	SeriesID                     *string                   `json:"SeriesId,omitempty"`
	SeriesName                   *string                   `json:"SeriesName,omitempty"`
	SeriesPrimaryImageTag        *string                   `json:"SeriesPrimaryImageTag,omitempty"`
	SeriesStudio                 *string                   `json:"SeriesStudio,omitempty"`
	SeriesTimerID                *string                   `json:"SeriesTimerId,omitempty"`
	ServerID                     *string                   `json:"ServerId,omitempty"`
	ShutterSpeed                 *float64                  `json:"ShutterSpeed"`
	Size                         *int64                    `json:"Size"`
	Software                     *string                   `json:"Software,omitempty"`
	SongCount                    *int64                    `json:"SongCount"`
	SortIndexNumber              *int64                    `json:"SortIndexNumber"`
	SortName                     *string                   `json:"SortName,omitempty"`
	SortParentIndexNumber        *int64                    `json:"SortParentIndexNumber"`
	SpecialFeatureCount          *int64                    `json:"SpecialFeatureCount"`
	StartDate                    *string                   `json:"StartDate"`
	Status                       *string                   `json:"Status,omitempty"`
	Studios                      []NameLongIDPair          `json:"Studios,omitempty"`
	Subviews                     []string                  `json:"Subviews,omitempty"`
	SupportsResume               *bool                     `json:"SupportsResume"`
	SupportsSync                 *bool                     `json:"SupportsSync"`
	SyncStatus                   *SyncJobItemStatus        `json:"SyncStatus,omitempty"`
	TagItems                     []NameLongIDPair          `json:"TagItems,omitempty"`
	Taglines                     []string                  `json:"Taglines,omitempty"`
	Tags                         []string                  `json:"Tags,omitempty"`
	TimerID                      *string                   `json:"TimerId,omitempty"`
	TimerType                    *LiveTvTimerType          `json:"TimerType,omitempty"`
	Type                         *string                   `json:"Type,omitempty"`
	UserData                     *UserItemDataDto          `json:"UserData,omitempty"`
	Video3DFormat                *Video3DFormat            `json:"Video3DFormat,omitempty"`
	Width                        *int64                    `json:"Width"`
}
